functions/src/events.ts, functions/src/types.ts, src/api/firebaseUtils.ts, src/types/Events.ts
Implements geofencing to `eventSignIn` and `eventSignOut` cloud functions. The user's client will send its current position to the cloud function and the distance will be checked if it's within the given acceptable range (Event radius + 10 meters to account for possible error).
=> Geofencing

src/screens/admin/CommitteeEdit.tsx, src/screens/events/EventInfo.tsx, src/screens/events/FinalizeEvent.tsx, src/screens/events/SetGeneralEventDetails.tsx, src/screens/events/UpdateEvent.tsx, src/screens/involvement/Committee.tsx, src/screens/involvement/CommitteeCard.tsx, src/screens/involvement/CommitteeTeamCard.tsx, src/types/Committees.ts, src/types/Events.ts
This PR include changes to make event host and committee team member more dynamic. The implementatoin before would simply save the user data and display it, which mean if a user changes their profile then the event host/ committee team member would not change. This new update will refetch user data when needed.
- #244
=> Event host & Committee Team Member update

functions/src/committees.ts, functions/src/index.ts, functions/src/pushNotification.ts, src/api/firebaseUtils.ts, src/navigation/AdminDashboardStack.tsx, src/navigation/ProfileSetupStack.tsx, src/screens/admin/AdminDashboard.tsx, src/screens/admin/CommitteeConfirm.tsx, src/screens/admin/CommitteeEdit.tsx, src/screens/events/EventInfo.tsx, src/screens/home/Settings.tsx, src/screens/involvement/Committee.tsx, src/screens/involvement/CommitteeCard.tsx, src/screens/onboarding/ProfileSetup.tsx, src/types/Committees.ts, src/types/Navigation.ts
**Revamp for joining a  commitee**
- a committee can be set to closed/open to members 
- If closed then a user must request to join.
- If open then users a free to join 
- An admin will be allowed to approve/deny membership 
- Adman can review number of request
- When approved/denied a member will be notified.
**Revamp on committee counting**
- created a committee update count function that can be ran manually
- Note: in the future will need to make this on a scehdule
**Add Member Committee List**
- Display all members in the committee
- Allow navigation to public profile
=> Committee changes

src/api/__tests__/firebaseUtils.test.ts, src/api/firebaseUtils.ts, src/screens/PublicProfile.tsx, src/screens/home/Settings.tsx, src/screens/involvement/CommitteeTeamCard.tsx, src/screens/onboarding/ProfileSetup.tsx, src/types/Navigation.ts, src/types/User.ts
- resume permanently private
- made email private
- can change email to public/private in settings
=> Privacy for Email and Resume

src/screens/resources/PointsLeaderboard.tsx
Modified point leaderboard slightly to use the normal rank card and separated user rank card with main leaderboard.
=> Point leaderboard personal card

app.json, src/api/firebaseUtils.ts, src/components/FlickrPhotoGallery.tsx, src/screens/PublicProfile.tsx, src/screens/home/Settings.tsx, src/screens/involvement/Committee.tsx
- #321 
- Add No user found if uid is empty in profile screen
- Fix variable naming
- change Flickr album
=> Account deletion

src/api/firebaseUtils.ts, src/navigation/AdminDashboardStack.tsx, src/screens/admin/AdminDashboard.tsx, src/screens/admin/LinkManager.tsx, src/screens/involvement/MemberSHPE.tsx, src/screens/resources/Resources.tsx, src/types/Links.ts, src/types/Navigation.ts
This PR makes all links on the application dynamic such that they can be changed my the link manager in admin screen. An admin is allowed the change the name, icon (optional). and the url.
The first five links are reserved for social media links found on resources screen
The next two links are reserved for membership links (chapter due, national due)
- #329
=> Link manager

shpe-app-web/app/(main)/points/page.tsx
The total points view of the points sheet.
=> init pointsheet

functions/src/resume.ts, functions/src/types/events.ts, shpe-app-web/app/types/events.ts, shpe-app-web/app/types/user.ts, src/api/firebaseUtils.ts, src/navigation/index.tsx, src/screens/admin/CommitteeEdit.tsx, src/screens/admin/QRCodeManager.tsx, src/screens/events/EventVerification.tsx, src/screens/events/Events.tsx, src/screens/events/SetGeneralEventDetails.tsx, src/screens/events/UpdateEvent.tsx, src/screens/home/Settings.tsx, src/screens/involvement/Committee.tsx, src/screens/involvement/MemberSHPE.tsx, src/screens/resources/OfficeHours.tsx, src/screens/resources/Resources.tsx, src/types/Events.ts, src/types/User.ts
All task completed listed in 
- #303 
- #352 
- #363 
- #362
=> Small changes and features

shpe-app-web/app/types/user.ts, src/api/firebaseUtils.ts, src/components/MemberCard.tsx, src/screens/admin/ShirtConfirm.tsx, src/types/Navigation.ts, src/types/User.ts
=> seperate member list for shirt picked up and not picked up

functions/src/events.ts, functions/src/index.ts, functions/src/types/events.ts, shpe-app-web/app/types/events.ts, src/api/firebaseUtils.ts, src/components/MemberCardMultipleSelect.tsx, src/navigation/AdminDashboardStack.tsx, src/screens/admin/AdminDashboard.tsx, src/screens/admin/InstagramPoints.tsx, src/screens/events/Events.tsx, src/screens/events/SetSpecificEventDetails.tsx, src/types/Events.ts, src/types/Navigation.ts
Implemented method for adding points for #WearItWednesday
- Create a cloud function similar to sign in but removed most retrictions (allow multiple sign in, no location restriction, no checking start, etc). Add instagramLogs field for record keeping. 
- Implemented InstagramPoint Screen that allows admin to select mutliple users and recieve points
- Add hiddenEvent field to hide the Instagram Point event, Also this give more flexibility to officers to keep the event list clean.
=> Instagram points

functions/src/types/events.ts, shpe-app-web/app/types/events.ts, src/api/firebaseUtils.ts, src/navigation/HomeStack.tsx, src/navigation/UserProfileStack.tsx, src/screens/events/EventVerification.tsx, src/screens/home/Home.tsx, src/screens/home/Ishpe.tsx, src/screens/home/OfficeHours.tsx, src/screens/userProfile/PublicProfile.tsx, src/screens/userProfile/Settings.tsx, src/types/events.ts, src/types/navigation.ts
This PR contains these changes
- add membershpe to user profile
- fix dup event in ishpe
- moved settings to home screen
- add out of range for sign in/out of event
=> Small changes

shpe-app-web/app/(main)/events/page.tsx
=> fix pending event

src/api/firebaseUtils.ts, src/screens/home/Home.tsx
- fix bug where event was not displaying when the exact time was the end time (#435)
- fix random sign out bug
=> Events list fix

src/screens/onboarding/ProfileSetup.tsx
- fix onboarding screen, button going out of screen for smaller devices
=> add scrollview to onboarding screen (#434)

src/screens/home/Members.tsx
=> fix scroll in directory

functions/src/events.ts
=> Added logging to cloud functions

src/screens/events/EventCard.tsx, src/screens/events/EventInfo.tsx, src/screens/events/Events.tsx, src/screens/events/SetSpecificEventDetails.tsx, src/screens/home/MemberSHPE.tsx, src/types/events.ts
=> hotfix for noPoints

shpe-app-web/app/(main)/committees/page.tsx, shpe-app-web/app/(main)/dashboard/page.tsx, shpe-app-web/app/(main)/events/page.tsx, shpe-app-web/app/(main)/layout.tsx, shpe-app-web/app/(main)/membership/page.tsx, shpe-app-web/app/(main)/tools/page.tsx, shpe-app-web/app/components/Navbar.tsx
Changed the original navbar to a horizontal format
- Got rid of the shpe logo
- removed the header from everyones pages
- edited the layot.tsx
=> New Navbar

src/screens/userProfile/PublicProfile.tsx
Fix back button for public profile display. In some stacks the public profile does not display back button. Is fixed now
=> Fix back button display

src/screens/events/EventInfo.tsx, src/screens/events/SetSpecificEventDetails.tsx, src/types/events.ts
- Default study hour buffer times to 0 start buffer and 15 min end buffer
- add clarifying text for study hour tracking system. We want users to know that they can leave the building to get food or do other activities but must be in Zach to scan qrcodes
- imrpove display for sign in and out attendance (i.e. if sign out points does not exist, dont attendance count for sign outt)
=> Study hour default

functions/package-lock.json, functions/package.json, functions/src/events.ts
This PR adds some enhancements to `eventSignIn` and `eventSignOut`
- Enhanced and more Verbose logging
- Updated packages for cloud-functions
- Fixes issue that allowed a user to arbitrarily sign in another user if they weren't privileged.
- closes https://github.com/TAMUSHPE/MobileApp/issues/492
The most notable fix is a check to ensure users cannot simply sign in for other users:
```js
// Only allow privileged users to sign-in for other users
const token = context.auth.token;
if (uid !== context.auth.uid && (token.admin !== true && token.officer !== true && token.developer !== true && token.secretary !== true && token.lead !== true && token.representative !== true)) {
functions.logger.warn(`${context.auth.token} attempted to sign in as ${uid} with invalid permissions.`);
throw new …
```
=> Event housekeeping

src/screens/committees/CommitteeCard.tsx, src/screens/committees/CommitteeInfo.tsx, src/screens/committees/Committees.tsx, src/screens/events/EventInfo.tsx
This PR is a UI update and has no change to the backend.
- Add "Meet the Team" Section
- Removed All Team Members (head/rep/lead) icon in committee card and committee info screen. Replaced by "Meet the Team" section
- Sort committee list by first the committee you're in, then my committee count
- Hide About section if no description created
- Remove "Leave" button after joining a committee, added a smaller text under logo called "Leave?"
- Rearrange Committee Logo, Name, and Committee Count in committee info screen. Since committee logo taking too much sapce.
- Change joined label to a shpe logo
=> Mini committee ui update

app.json, src/components/LocationPicker.tsx
=> fix android map with restricted api key

shpe-app-web/app/(main)/tools/page.tsx, shpe-app-web/app/(main)/tools/shirt-tracker/page.tsx, shpe-app-web/app/api/firebaseUtils.ts, shpe-app-web/app/components/Navbar.tsx
- Add  pick up shirt tracker sheet
- Fix navbar highlight for nested routing
- improve tools display
=> Shirt pickup

shpe-app-web/app/(main)/tools/shirt-tracker/page.tsx
- add column "offical member" to pick up shirt
=> add offical member column

shpe-app-web/app/(main)/membership/page.tsx, shpe-app-web/app/(main)/points/page.tsx, shpe-app-web/app/(main)/tools/shirt-tracker/page.tsx
urgently need somesort of caching for website. Since we are doing too many reads.
=> Simple local storage

shpe-app-web/app/(main)/tools/shirt-tracker/page.tsx, shpe-app-web/app/api/firebaseUtils.ts
=> fix N/A user in pick up sheet

src/api/firebaseUtils.ts, src/components/MOTMCard.tsx, src/screens/committees/CommitteeInfo.tsx, src/screens/events/Events.tsx, src/screens/home/Home.tsx
- simplied event list into "Main", "Intramural", "Committee"
- show hidden event to only privilege user
- fix for MOTM inital load
- Test the Events list screen
=> Event UI update

src/screens/events/EventInfo.tsx
fix for manual sign in and out message
=> fix manual sign in and out message

src/api/firebaseUtils.ts, src/screens/committees/CommitteeInfo.tsx
=> fix qrcode undefined

src/api/firebaseUtils.ts, src/screens/events/EventInfo.tsx, src/screens/events/Events.tsx, src/screens/userProfile/PersonalEventLog.tsx
There was some confusion on whether or not a member recieved points for their #wearitwednesday post. Now there is a specific display for instagram points
- #557 
- removed info icon and change study hour text
=> Instagram points log display

functions/src/events.ts
Redid how points are calculated on the backend to use a single function instead of business logic in both.
closes https://github.com/TAMUSHPE/MobileApp/issues/486
=> Point calculation

functions/src/types/events.ts, src/api/firebaseUtils.ts, src/screens/events/EventVerification.tsx, src/types/events.ts
- fixes https://github.com/TAMUSHPE/MobileApp/issues/515
=> Added Geolocation status

package.json, src/api/__tests__/firebaseUtils.test.ts, src/api/firebaseUtils.ts, src/screens/events/Events.tsx, yarn.lock
- refactor getAttendancNumber Function
- Update firebase 10 -> firebase 11
- fix today's event filter
=> Refactor attendance function

src/screens/home/Home.tsx
Is this all we wanted to do? Should i keep the button there or move it to resources tab; unsure if its vital enough to take up that real estate
=> added link to merch button'
